name: "0-Container Deployment Pipeline"

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  integration:
    uses: ./.github/workflows/integrate-python-app.yml
    permissions:
      contents: read

  delivery:
    needs: [integration]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Print image digest
        run: echo "Image digest is ${{ steps.build-and-push.outputs.digest }}"

      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          DIGEST="${{ steps.build-and-push.outputs.digest }}"
          echo "Signing ${IMAGE}@${DIGEST}"
          cosign sign --yes "${IMAGE}@${DIGEST}"

  deploy-staging:
    needs: [delivery]
    uses: ./.github/workflows/deploy-aws-app-runner.yml
    with:
      environment: Staging
    permissions:
      packages: read
    secrets: inherit

  deploy-production:
    needs: [deploy-staging]
    uses: ./.github/workflows/deploy-aws-app-runner.yml
    with:
      environment: Production
    permissions:
      packages: read
    secrets: inherit
