name: "Sign Container Image"

on:
  push:
    branches: [ main ]

jobs:
  sign-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write  # This is crucial for signing permissions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Get exact image reference
        id: image-ref
        run: |
          # Force lowercase repository name
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=${REPO_NAME}" >> $GITHUB_OUTPUT

      - name: Sign image with Cosign (using tag reference)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          # Use the lowercase repository name
          IMAGE_REF="ghcr.io/${{ steps.image-ref.outputs.repo_name }}:main"
          
          # Sign using the tag reference (with --force flag)
          echo "Signing image: ${IMAGE_REF}"
          cosign sign --force --yes "${IMAGE_REF}"