name: "Sign Container Image"

on:
  push:
    branches: [ main ]

jobs:
  sign-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cosign and Crane
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.0.0'
      
      - name: Install Crane
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          curl -sL https://github.com/google/go-containerregistry/releases/download/v0.13.0/go-containerregistry_Linux_x86_64.tar.gz | \
            sudo tar -xz -C /usr/local/bin crane

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          # Use exact repository name (case-sensitive)
          REPO_NAME="${{ github.repository }}"
          IMAGE_TAG="main"
          IMAGE_REF="ghcr.io/${REPO_NAME}:${IMAGE_TAG}"
          
          # Get digest using crane
          echo "Getting digest for ${IMAGE_REF}"
          DIGEST=$(crane digest "${IMAGE_REF}")
          
          # Sign using digest (recommended approach)
          echo "Signing image: ghcr.io/${REPO_NAME}@${DIGEST}"
          cosign sign --yes "ghcr.io/${REPO_NAME}@${DIGEST}"