name: Sign Container Image

on:
  push:
    branches: [ main ]

jobs:
  sign-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # 🔐 Это важно для OIDC keyless signing
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign image with Cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign ghcr.io/paul-dimension/ci_cd_for_container_images_2:main